name: Deploy to Hostnet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to Hostnet via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ssh.cyz0ptrz6.service.one
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "index.html"
          target: "/webroots/sites/hesseldevries.com/"
          overwrite: true
